@extends('layouts.admin')

@section('title', 'Add client')

{{--
    Add a client — admin.clients.create → POST admin.clients.store (phase-05 §6.7). A client ID is generated by
    DocumentNumberService; the portal starts switched off.

    Controller variables (Admin\ClientController@create): $client (a fresh App\Models\Crm\Client), $clientTypeOptions,
    $sourceOptions, $accountManagerOptions, $defaultCurrency, $defaultPaymentTermsDays, $defaultTaxRate
    (see admin/clients/partials/form).
--}}

@section('header')
    <x-ui.page-header title="Add client" subtitle="Most clients arrive by converting a won lead; add one here when they did not." icon="building-office" :back="route('admin.clients.index')" />
@endsection

@section('content')
    @include('admin.clients.partials.form', ['client' => $client ?? new \App\Models\Crm\Client()])
@endsection
