<?php

declare(strict_types=1);

namespace App\Models\Hr;

use App\Enums\PayrollRunStatus;
use App\Enums\PayrollRunType;
use App\Models\Branch;
use App\Models\Concerns\Blameable;
use App\Models\Concerns\LogsActivityWithContext;
use App\Models\User;
use App\Services\Hr\Exceptions\ImmutablePayrollAttributeException;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Carbon;

/**
 * One payroll run (phase-07 §2.23, requirement §28).
 *
 * **`locked_at` is a one-way door** (HR-15). After it, every money column on every item is frozen, the
 * period's attendance is locked with it (HR-18), and there is deliberately **no unlock** — an unlock is an
 * edit of paid money with extra steps ([D-HR-6]). A wrong slip is corrected by a correction run that
 * references the original, which leaves both the mistake and the fix on the record.
 *
 * `day_basis`, `lop_basis`, `tax_mode` and `settings_snapshot` are **snapshots of the settings that shaped
 * the calculation**. Somebody changing `hr.payroll_day_basis` next year must not silently change what last
 * March's slip means, and without the snapshot it would.
 *
 * `regular_guard` carries `uq_pr_regular`: one live regular run per branch per month, so a second March
 * payroll cannot be generated by accident while the first exists.
 */
class PayrollRun extends Model
{
    use Blameable;
    use LogsActivityWithContext;

    /** What may still move once the run is locked (HR-15). */
    public const UPDATABLE_AFTER_LOCK = [
        'status',
        'paid_at',
        'total_paid',
        'notes',
        'cancelled_at',
        'cancelled_by',
        'cancellation_reason',
        'updated_at',
        'updated_by',
    ];

    protected $table = 'payroll_runs';

    /**
     * @var list<string>
     */
    protected $fillable = [
        'title',
        'branch_id',
        'run_type',
        'parent_run_id',
        'period_year',
        'period_month',
        'period_start',
        'period_end',
        'payment_date',
        'notes',
    ];

    /**
     * @var array<string, mixed>
     */
    protected $attributes = [
        'status' => 'draft',
        'run_type' => 'regular',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'branch_id' => 'integer',
            'run_type' => PayrollRunType::class,
            'parent_run_id' => 'integer',
            'period_year' => 'integer',
            'period_month' => 'integer',
            'period_start' => 'date',
            'period_end' => 'date',
            'payment_date' => 'date',
            'status' => PayrollRunStatus::class,
            'employee_count' => 'integer',
            'total_gross' => 'decimal:2',
            'total_deductions' => 'decimal:2',
            'total_net' => 'decimal:2',
            'total_paid' => 'decimal:2',
            'settings_snapshot' => 'array',
            'generated_at' => 'datetime',
            'generated_by' => 'integer',
            'locked_at' => 'datetime',
            'locked_by' => 'integer',
            'paid_at' => 'datetime',
            'cancelled_at' => 'datetime',
            'cancelled_by' => 'integer',
        ];
    }

    protected static function booted(): void
    {
        static::updating(static function (PayrollRun $run): void {
            // The lock only bites on a run that was *already* locked — the write that locks it is legal.
            // getRawOriginal(): a datetime cast would hand back a Carbon, never null-compared cleanly.
            if ($run->getRawOriginal('locked_at') === null) {
                return;
            }

            $touched = array_values(array_diff(array_keys($run->getDirty()), self::UPDATABLE_AFTER_LOCK));

            if ($touched !== []) {
                throw ImmutablePayrollAttributeException::locked('PayrollRun', $run->getKey() ?? 'new', $touched);
            }
        });

        static::deleting(static function (PayrollRun $run): void {
            throw ImmutablePayrollAttributeException::locked(
                'PayrollRun',
                $run->getKey() ?? 'new',
                ['the run itself — cancellation is a status, not a delete (HR-16)'],
            );
        });
    }

    public function moduleSlug(): string
    {
        return 'payroll';
    }

    protected function activityModule(): ?string
    {
        return 'payroll';
    }

    /**
     * Is the money on this run frozen?
     */
    public function isLocked(): bool
    {
        return $this->locked_at !== null || $this->status->isLocked();
    }

    /**
     * A human label for the period, for a message that has to name it.
     *
     * Built from the year and the month rather than from `period_start`, so a screen that selected only
     * the columns it needs still reads "August 2026" instead of falling back to "2026-08".
     */
    public function periodLabel(): string
    {
        if ($this->period_year === null || $this->period_month === null) {
            return '—';
        }

        return Carbon::create((int) $this->period_year, (int) $this->period_month, 1)->format('F Y');
    }

    public function branch(): BelongsTo
    {
        return $this->belongsTo(Branch::class, 'branch_id');
    }

    public function parentRun(): BelongsTo
    {
        return $this->belongsTo(self::class, 'parent_run_id');
    }

    public function correctionRuns(): HasMany
    {
        return $this->hasMany(self::class, 'parent_run_id');
    }

    public function generator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'generated_by');
    }

    public function locker(): BelongsTo
    {
        return $this->belongsTo(User::class, 'locked_by');
    }

    public function canceller(): BelongsTo
    {
        return $this->belongsTo(User::class, 'cancelled_by');
    }

    public function items(): HasMany
    {
        return $this->hasMany(PayrollRunItem::class, 'payroll_run_id');
    }

    public function lockedAttendances(): HasMany
    {
        return $this->hasMany(Attendance::class, 'locked_by_payroll_run_id');
    }

    public function lockedSummaries(): HasMany
    {
        return $this->hasMany(AttendanceMonthlySummary::class, 'locked_by_payroll_run_id');
    }
}
