<?php

declare(strict_types=1);

namespace App\Services\Cms\Support;

use App\Enums\Cms\ContentStatus;
use App\Enums\Cms\ImageProfile;
use App\Enums\Cms\MediaCollection;
use App\Models\Cms\MediaAsset;
use App\Models\Cms\Technology;
use App\Services\Cms\CacheVersion;
use App\Services\Cms\CmsAuditor;
use App\Services\Cms\Exceptions\ContentRuleException;
use App\Services\Cms\Exceptions\UnsupportedUploadException;
use App\Services\Cms\MediaService;
use App\Services\Cms\SeoService;
use App\Support\Money;
use App\Support\RichText;
use App\Support\SettingsRepository;
use App\Support\SlugGenerator;
use Closure;
use Illuminate\Database\ConnectionInterface;
use Illuminate\Database\DatabaseManager;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\UniqueConstraintViolationException;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Str;
use Throwable;

/**
 * The write-side plumbing every phase-04 content service shares — composed, not inherited, so each
 * service keeps the exact `final class` shape its contract states (§6.2 – §6.10).
 *
 * One implementation of each cross-cutting rule:
 *
 *   · **Images go through Phase 3's `MediaService` (D24).** An upload becomes a `media_assets` row and the
 *     caller stores its id; a refused upload is a 422 on the form field, never a stack trace. A library
 *     pick is checked to be a live image. No binary is ever deleted here.
 *   · **Rich text is sanitised on write with `RichText::sanitize()` (D25)**, plain text is stripped of tags
 *     and control characters — there is no second sanitiser.
 *   · **SEO is written only through `SeoService::save()` (D23)**, from the `seo.*` block of the payload.
 *   · **Slugs** are generated by `SlugGenerator` (through the models' `HasSlug`) and a 1062 on the slug
 *     index is retried up to three times inside a savepoint (§6.1 invariant 5). A hand-entered slug that
 *     collides is a 422 on `slug`.
 *   · **Audit**: named acts (status, slug, moderation, reorder …) are written through `CmsAuditor` with the
 *     request context; `quietly()` suppresses the model's generic "updated" row for that one write so an
 *     act is recorded once, not twice.
 *   · **Public cache**: a change a visitor can see bumps Phase 3's version stamp after commit (D22).
 */
final class ContentHelper
{
    private const SLUG_ATTEMPTS = 3;

    public function __construct(
        private readonly DatabaseManager $db,
        private readonly MediaService $media,
        private readonly SeoService $seo,
        private readonly CmsAuditor $auditor,
        private readonly CacheVersion $cache,
        private readonly SettingsRepository $settings,
    ) {}

    public function connection(): ConnectionInterface
    {
        return $this->db->connection();
    }

    /**
     * @template TResult
     *
     * @param  Closure(): TResult  $callback
     * @return TResult
     */
    public function transaction(Closure $callback): mixed
    {
        return $this->db->connection()->transaction($callback);
    }

    public function settings(): SettingsRepository
    {
        return $this->settings;
    }

    public function auditor(): CmsAuditor
    {
        return $this->auditor;
    }

    public function actorId(): ?int
    {
        return $this->auditor->actorId();
    }

    /*
    |--------------------------------------------------------------------------
    | Images (D24)
    |--------------------------------------------------------------------------
    */

    /**
     * Store an upload in the media library and return the new (or de-duplicated) asset.
     */
    public function storeImage(UploadedFile $file, MediaCollection $collection, ImageProfile $profile, string $field, array $meta = []): MediaAsset
    {
        try {
            $asset = $this->media->store($file, $collection, $profile, $meta);
        } catch (UnsupportedUploadException $exception) {
            throw ContentRuleException::uploadRefused($field, $exception->getMessage());
        }

        if (! $asset->isImage()) {
            throw ContentRuleException::uploadRefused($field, 'Upload an image (JPEG, PNG, WebP, GIF or AVIF).');
        }

        return $asset;
    }

    /**
     * Resolve a `*_media_id` for a column: an upload wins, then an explicit library pick (`$data[$column]`),
     * then a `remove_*` flag; otherwise the current value is kept.
     *
     * @param  array<string, mixed>  $data
     */
    public function resolveMediaColumn(
        array $data,
        string $column,
        ?UploadedFile $upload,
        MediaCollection $collection,
        ImageProfile $profile,
        string $field,
        ?int $current,
        string $removeFlag = 'remove_image',
    ): ?int {
        if ($upload instanceof UploadedFile) {
            return (int) $this->storeImage($upload, $collection, $profile, $field)->getKey();
        }

        if (array_key_exists($column, $data)) {
            return $this->pickedMedia($data[$column], $column);
        }

        if (filter_var($data[$removeFlag] ?? false, FILTER_VALIDATE_BOOLEAN)) {
            return null;
        }

        return $current;
    }

    /**
     * A media id picked from the library: null, or a live image asset.
     */
    public function pickedMedia(mixed $value, string $field): ?int
    {
        if ($value === null || $value === '' || $value === 0 || $value === '0') {
            return null;
        }

        if (! is_numeric($value) || (int) $value < 1) {
            throw ContentRuleException::refuse($field, 'Choose an image from the media library.');
        }

        $asset = MediaAsset::query()->whereKey((int) $value)->first();

        if (! $asset instanceof MediaAsset || ! $asset->isImage()) {
            throw ContentRuleException::refuse($field, 'The chosen image no longer exists in the media library.');
        }

        return (int) $asset->getKey();
    }

    /**
     * Refresh `usage_count` for the given assets once the transaction commits (never a binary delete).
     *
     * @param  array<int, int|null>  $ids
     */
    public function recountMediaAfterCommit(array $ids): void
    {
        $ids = array_values(array_unique(array_filter(array_map('intval', $ids))));

        if ($ids === []) {
            return;
        }

        $this->db->connection()->afterCommit(function () use ($ids): void {
            try {
                $this->media->recountUsage($ids);
            } catch (Throwable $exception) {
                report($exception);
            }
        });
    }

    /*
    |--------------------------------------------------------------------------
    | Text (D25)
    |--------------------------------------------------------------------------
    */

    /**
     * Plain text: control characters removed, tags stripped, trimmed, truncated; empty → null.
     */
    public function plain(mixed $value, ?int $limit = null): ?string
    {
        if (! is_scalar($value)) {
            return null;
        }

        $text = (string) preg_replace('~[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]~u', '', (string) $value);
        $text = trim(strip_tags($text));

        if ($text === '') {
            return null;
        }

        return $limit === null ? $text : mb_substr($text, 0, $limit);
    }

    /**
     * Rich text through the one sanitiser; an empty result → null.
     */
    public function rich(mixed $value): ?string
    {
        if (! is_scalar($value)) {
            return null;
        }

        $html = trim(RichText::sanitize((string) $value));

        return trim(strip_tags($html, '<img><iframe><video>')) === '' ? null : $html;
    }

    /**
     * An ordered list of trimmed, non-empty strings (§6.4 invariant 2); an empty list → null.
     */
    public function stringList(mixed $value, int $maxItems, int $maxLength, string $field): ?array
    {
        if ($value === null || $value === '') {
            return null;
        }

        if (is_string($value)) {
            $value = preg_split('~\R~u', $value);
        }

        if (! is_array($value)) {
            throw ContentRuleException::refuse($field, 'Provide a list of entries.');
        }

        $items = [];

        foreach ($value as $item) {
            $text = $this->plain($item);

            if ($text === null) {
                continue;
            }

            if (mb_strlen($text) > $maxLength) {
                throw ContentRuleException::refuse($field, sprintf('Each entry may be at most %d characters.', $maxLength));
            }

            $items[] = $text;
        }

        if (count($items) > $maxItems) {
            throw ContentRuleException::tooManyItems($field, $maxItems);
        }

        return $items === [] ? null : $items;
    }

    /**
     * An absolute http(s) URL with a host, or null.
     */
    public function url(mixed $value, string $field, int $limit = 255): ?string
    {
        $url = $this->plain($value);

        if ($url === null) {
            return null;
        }

        $scheme = strtolower((string) parse_url($url, PHP_URL_SCHEME));
        $host = (string) parse_url($url, PHP_URL_HOST);

        if (! in_array($scheme, ['http', 'https'], true) || $host === '' || mb_strlen($url) > $limit) {
            throw ContentRuleException::invalidUrl($field);
        }

        return $url;
    }

    /**
     * A money value for a `decimal(15,2)` column, straight from the validated string through `Money`
     * (§6.4 invariant 1) — never a float, never arithmetic. Null / '' → null.
     */
    public function money(mixed $value, string $field): ?string
    {
        if ($value === null || $value === '') {
            return null;
        }

        if (! is_string($value) && ! is_int($value)) {
            throw ContentRuleException::refuse($field, 'Enter the amount as a number with at most two decimals.');
        }

        $raw = trim((string) $value);

        if (preg_match('~^\d{1,3}(?:,?\d{3})*(?:\.\d{1,2})?$|^\d+(?:\.\d{1,2})?$~', $raw) !== 1) {
            throw ContentRuleException::refuse($field, 'Enter the amount as a number with at most two decimals.');
        }

        try {
            $amount = Money::of($raw);
        } catch (Throwable) {
            throw ContentRuleException::refuse($field, 'Enter the amount as a number with at most two decimals.');
        }

        if (Money::isNegative($amount) || Money::greaterThan($amount, '9999999999999.99')) {
            throw ContentRuleException::refuse($field, 'The amount is out of range.');
        }

        return $amount;
    }

    public function bool(mixed $value, bool $default = false): bool
    {
        if ($value === null || $value === '') {
            return $default;
        }

        return filter_var($value, FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE) ?? $default;
    }

    public function int(mixed $value, ?int $default = null, ?int $min = null, ?int $max = null): ?int
    {
        if ($value === null || $value === '' || ! is_numeric($value)) {
            return $default;
        }

        $int = (int) $value;

        if ($min !== null) {
            $int = max($min, $int);
        }

        if ($max !== null) {
            $int = min($max, $int);
        }

        return $int;
    }

    /**
     * A positive id or null — for the deferred-FK columns (§2.1), which point at nothing yet.
     */
    public function id(mixed $value): ?int
    {
        return is_numeric($value) && (int) $value > 0 ? (int) $value : null;
    }

    /*
    |--------------------------------------------------------------------------
    | Slugs (§6.1)
    |--------------------------------------------------------------------------
    */

    /**
     * The slug an admin typed, normalised, or null when none was entered. A reserved or malformed one is
     * refused on `slug` (the Form Request refuses it first; this is the service-side net).
     *
     * @param  array<string, mixed>  $data
     */
    public function manualSlug(array $data): ?string
    {
        $slug = $data['slug'] ?? null;

        if (! is_string($slug) || trim($slug) === '') {
            return null;
        }

        $slug = Str::lower(trim($slug));

        if (preg_match(SlugGenerator::PATTERN, $slug) !== 1) {
            throw ContentRuleException::refuse('slug', 'Use lower-case letters, numbers and single hyphens only.');
        }

        if (SlugGenerator::isReserved($slug)) {
            throw ContentRuleException::refuse('slug', 'This permalink is reserved. Choose another.');
        }

        return $slug;
    }

    /**
     * Save a sluggable model; a generated slug that loses a race is regenerated (three attempts), a
     * hand-entered slug that is taken is a 422. Runs the save in a savepoint so a 1062 never poisons
     * the caller's transaction.
     */
    public function saveWithSlug(Model $model, bool $manual, int $max = 180, string $column = 'slug'): void
    {
        for ($attempt = 1; ; $attempt++) {
            try {
                $this->db->connection()->transaction(static fn () => $model->save());

                return;
            } catch (UniqueConstraintViolationException $exception) {
                if (! str_contains($exception->getMessage(), $column)) {
                    throw $exception;
                }

                if ($manual) {
                    throw ContentRuleException::refuse($column, 'This permalink is already in use. Choose another.');
                }

                if ($attempt >= self::SLUG_ATTEMPTS) {
                    throw ContentRuleException::slugUnavailable();
                }

                $source = method_exists($model, 'sluggableSource') ? (string) $model->sluggableSource() : '';
                $previous = (string) $model->getAttribute($column);
                $next = SlugGenerator::make($source, $model->getTable(), $model->exists ? (int) $model->getKey() : null, $column, $max);

                if ($next === $previous) {
                    $tail = '-'.Str::lower(Str::random(4));
                    $next = rtrim(substr($next, 0, $max - strlen($tail)), '-').$tail;
                }

                $model->setAttribute($column, $next);
            }
        }
    }

    /**
     * The `slug_changed` activity entry (§6.1, §10.5): old → new, and whether the record was already public.
     */
    public function auditSlugChange(Model $model, string $module, string $old, string $new, bool $wasPublished): void
    {
        $this->auditor->record(
            module: $module,
            description: sprintf('Permalink changed from "%s" to "%s"', $old, $new),
            subject: $model,
            properties: [
                'old' => ['slug' => $old],
                'attributes' => ['slug' => $new],
                'was_published' => $wasPublished,
            ],
            event: 'slug_changed',
        );
    }

    /*
    |--------------------------------------------------------------------------
    | SEO (D23)
    |--------------------------------------------------------------------------
    */

    /**
     * Write the `seo.*` block of a form payload through `SeoService::save()` — the only SEO writer.
     *
     * @param  array<string, mixed>  $data
     */
    public function saveSeo(Model $model, array $data): void
    {
        $seo = $data['seo'] ?? null;

        if (! is_array($seo) || $seo === []) {
            return;
        }

        $this->seo->save($model, array_intersect_key($seo, array_flip(SeoService::WRITABLE)));
    }

    /*
    |--------------------------------------------------------------------------
    | Content status (services, portfolio items, team members, success stories)
    |--------------------------------------------------------------------------
    */

    /**
     * Move a `ContentStatus` row to `$to` (§6.4 invariant 4): publishing requires a non-empty name/title
     * and slug, never alters `sort_order`, and writes one `status_changed` entry with the old and new
     * status. `scheduled` belongs to the blog alone — these catalogues publish or stay drafts. A move to
     * the current status changes nothing and logs nothing. Call inside the service's transaction.
     *
     * @param  (Closure(Model): void)|null  $beforePublish  an extra publish gate (the portfolio alt-text rule)
     */
    public function changeContentStatus(
        Model $model,
        ContentStatus $to,
        string $module,
        string $label,
        string $nameColumn = 'name',
        ?Closure $beforePublish = null,
        ?string $reason = null,
        bool $requiresSlug = true,
    ): Model {
        $current = $model->getAttribute('status');
        $from = $current instanceof ContentStatus ? $current : (ContentStatus::tryFrom((string) $current) ?? ContentStatus::Draft);

        if ($from === $to) {
            return $model;
        }

        if ($to === ContentStatus::Scheduled) {
            throw ContentRuleException::cannotSchedule($label);
        }

        if ($to === ContentStatus::Published) {
            if (trim((string) $model->getAttribute($nameColumn)) === '' || ($requiresSlug && trim((string) $model->getAttribute('slug')) === '')) {
                throw ContentRuleException::publishRequirements();
            }

            if ($beforePublish !== null) {
                $beforePublish($model);
            }
        }

        $this->quietly($model, function () use ($model, $to): void {
            $model->setAttribute('status', $to);
            $model->save();
        });

        $this->audit(
            $module,
            sprintf('%s "%s" moved from %s to %s', $label, (string) $model->getAttribute($nameColumn), $from->label(), $to->label()),
            $model,
            ['old' => ['status' => $from->value], 'attributes' => ['status' => $to->value]],
            $reason,
            'status_changed',
        );

        if ($from->isPublic() || $to->isPublic()) {
            $this->flushPublicCache(sprintf('%s "%s" %s', $label, (string) $model->getAttribute($nameColumn), $to->value));
        }

        return $model;
    }

    /**
     * A `ContentStatus` from form input (enum or value); null when absent, 422 when not a status.
     */
    public function contentStatus(mixed $value, string $field = 'status'): ?ContentStatus
    {
        if ($value === null || $value === '') {
            return null;
        }

        if ($value instanceof ContentStatus) {
            return $value;
        }

        return ContentStatus::tryFrom(is_scalar($value) ? (string) $value : '')
            ?? throw ContentRuleException::refuse($field, 'Choose a valid status.');
    }

    /**
     * Replace an ordered technology pivot (`service_technology` / `portfolio_item_technology`) with the
     * given ids, in the given order (`sort_order` 1..n). Unknown ids are a 422. Returns the ids before and
     * after, for the audit entry.
     *
     * @param  array<int, int|string>  $technologyIds
     * @return array{old: list<int>, new: list<int>}
     */
    public function syncTechnologies(string $pivot, string $ownerColumn, int $ownerId, array $technologyIds, string $field = 'technology_ids'): array
    {
        $ids = [];

        foreach ($technologyIds as $id) {
            if (! is_numeric($id) || (int) $id < 1) {
                throw ContentRuleException::refuse($field, 'Choose technologies from the list.');
            }

            $ids[(int) $id] = (int) $id;
        }

        $ids = array_values($ids);

        if ($ids !== [] && Technology::query()->whereIn('id', $ids)->count() !== count($ids)) {
            throw ContentRuleException::refuse($field, 'One of the chosen technologies no longer exists.');
        }

        $connection = $this->db->connection();
        $old = $connection->table($pivot)->where($ownerColumn, $ownerId)->orderBy('sort_order')->pluck('technology_id')->map('intval')->all();

        if ($old === $ids) {
            return ['old' => $old, 'new' => $ids];
        }

        $connection->table($pivot)->where($ownerColumn, $ownerId)->delete();

        $rows = [];

        foreach ($ids as $position => $technologyId) {
            $rows[] = [$ownerColumn => $ownerId, 'technology_id' => $technologyId, 'sort_order' => $position + 1];
        }

        if ($rows !== []) {
            $connection->table($pivot)->insert($rows);
        }

        return ['old' => $old, 'new' => $ids];
    }

    /**
     * Flip `is_featured` with one named entry (`featured` / `unfeatured`).
     */
    public function toggleFlag(Model $model, string $column, string $module, string $label, string $nameColumn, string $onEvent, string $offEvent): Model
    {
        $value = ! (bool) $model->getAttribute($column);

        $this->quietly($model, function () use ($model, $column, $value): void {
            $model->setAttribute($column, $value);
            $model->save();
        });

        $this->audit(
            $module,
            sprintf('%s "%s" %s', $label, (string) $model->getAttribute($nameColumn), $value ? $onEvent : $offEvent),
            $model,
            ['old' => [$column => ! $value], 'attributes' => [$column => $value]],
            null,
            $value ? $onEvent : $offEvent,
        );

        return $model;
    }

    /*
    |--------------------------------------------------------------------------
    | Audit + cache
    |--------------------------------------------------------------------------
    */

    /**
     * Run a write on the model without its generic `LogsActivityWithContext` row — for acts the caller
     * records itself, with a name and a reason.
     *
     * @template TResult
     *
     * @param  Closure(): TResult  $callback
     * @return TResult
     */
    public function quietly(Model $model, Closure $callback): mixed
    {
        $toggle = method_exists($model, 'disableLogging') && method_exists($model, 'enableLogging');

        if ($toggle) {
            $model->disableLogging();
        }

        try {
            return $callback();
        } finally {
            if ($toggle) {
                $model->enableLogging();
            }
        }
    }

    /**
     * @param  array<string, mixed>  $properties
     */
    public function audit(string $module, string $description, ?Model $subject = null, array $properties = [], ?string $reason = null, ?string $event = null): void
    {
        $this->auditor->record($module, $description, $subject, $properties, $reason, $event);
    }

    /**
     * Bump the public cache version once the surrounding transaction commits (D22).
     */
    public function flushPublicCache(string $reason): void
    {
        try {
            $this->cache->bumpAfterCommit(mb_substr($reason, 0, 200));
        } catch (Throwable $exception) {
            report($exception);
        }
    }
}
