<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Route guard manifest (D60; phase-24-25 §6.1, §13.2; build-order E4)
|--------------------------------------------------------------------------
|
| One row per route: its methods, its middleware exactly as `Route::gatherMiddleware()` reports it, the
| exact `can:` permission — or, for a route with none, a written `rationale` saying why it is deliberately
| reachable without one, so "I forgot the permission" can never look like "this route is public" — the
| panel, and whether it changes state. Phase 24's `audit:manifest --check` (SEC-01, SEC-20) fails on a route
| with no row and on a row whose route no longer exists.
|
| Append-only per phase: each phase adds its own rows, under its own banner, as part of its definition of
| done, and never edits another phase's. `owner_phase` records whose row it is (for --coverage).
|
| Row shape:
|   'route'          route name
|   'methods'        as Route::methods() reports them (GET routes include HEAD)
|   'middleware'     as Route::gatherMiddleware() reports them, in order
|   'permission'     the `can:` permission ("module.ability", declared by PermissionRegistry), or null
|   'panel'          admin | collaborator | student | teacher | client | public
|   'state_changing' true for POST / PUT / PATCH / DELETE
|   'rationale'      required when 'permission' is null; null otherwise
|   'owner_phase'    the phase that ships the route
|
*/

return [

    /*
    |----------------------------------------------------------------------
    | Phase 3 — public website CMS (85 routes: 78 admin.website.*, 7 site.*)
    |----------------------------------------------------------------------
    | tests/Feature/Cms/Http/CmsManifestTest keeps these rows equal to the live route table.
    */
    [
        'route' => 'admin.website.cache.flush',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_sections', 'can:website_sections.change_status', 'throttle:6,1,cms-cache-flush'],
        'permission' => 'website_sections.change_status',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.cta-blocks.destroy',
        'methods' => ['DELETE'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_cta_blocks', 'can:website_cta_blocks.delete'],
        'permission' => 'website_cta_blocks.delete',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.cta-blocks.edit',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_cta_blocks', 'can:website_cta_blocks.view'],
        'permission' => 'website_cta_blocks.view',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.cta-blocks.index',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_cta_blocks', 'can:website_cta_blocks.view_any'],
        'permission' => 'website_cta_blocks.view_any',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.cta-blocks.store',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_cta_blocks', 'can:website_cta_blocks.create'],
        'permission' => 'website_cta_blocks.create',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.cta-blocks.toggle',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_cta_blocks', 'can:website_cta_blocks.change_status'],
        'permission' => 'website_cta_blocks.change_status',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.cta-blocks.update',
        'methods' => ['PUT'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_cta_blocks', 'can:website_cta_blocks.edit'],
        'permission' => 'website_cta_blocks.edit',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.cta-blocks.usage',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_cta_blocks', 'can:website_cta_blocks.view'],
        'permission' => 'website_cta_blocks.view',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.faq-categories.destroy',
        'methods' => ['DELETE'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:faq_categories', 'can:faq_categories.delete'],
        'permission' => 'faq_categories.delete',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.faq-categories.index',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:faq_categories', 'can:faq_categories.view_any'],
        'permission' => 'faq_categories.view_any',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.faq-categories.reorder',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:faq_categories', 'can:faq_categories.edit'],
        'permission' => 'faq_categories.edit',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.faq-categories.store',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:faq_categories', 'can:faq_categories.create'],
        'permission' => 'faq_categories.create',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.faq-categories.update',
        'methods' => ['PUT'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:faq_categories', 'can:faq_categories.edit'],
        'permission' => 'faq_categories.edit',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.faqs.destroy',
        'methods' => ['DELETE'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:faqs', 'can:faqs.delete'],
        'permission' => 'faqs.delete',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.faqs.index',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:faqs', 'can:faqs.view_any'],
        'permission' => 'faqs.view_any',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.faqs.reorder',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:faqs', 'can:faqs.edit'],
        'permission' => 'faqs.edit',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.faqs.store',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:faqs', 'can:faqs.create'],
        'permission' => 'faqs.create',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.faqs.toggle',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:faqs', 'can:faqs.change_status'],
        'permission' => 'faqs.change_status',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.faqs.update',
        'methods' => ['PUT'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:faqs', 'can:faqs.edit'],
        'permission' => 'faqs.edit',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.index',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_sections', 'can:website_sections.view_any'],
        'permission' => 'website_sections.view_any',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.media.destroy',
        'methods' => ['DELETE'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_media', 'can:website_media.delete'],
        'permission' => 'website_media.delete',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.media.index',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_media', 'can:website_media.view_any'],
        'permission' => 'website_media.view_any',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.media.regenerate',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_media', 'can:website_media.edit', 'throttle:6,1,cms-media-regenerate'],
        'permission' => 'website_media.edit',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.media.show',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_media', 'can:website_media.view'],
        'permission' => 'website_media.view',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.media.store',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_media', 'can:website_media.upload', 'throttle:60,1,cms-media-upload'],
        'permission' => 'website_media.upload',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.media.update',
        'methods' => ['PUT'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_media', 'can:website_media.edit'],
        'permission' => 'website_media.edit',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.media.usage',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_media', 'can:website_media.view'],
        'permission' => 'website_media.view',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.menu-items.destroy',
        'methods' => ['DELETE'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:menus', 'can:menus.delete'],
        'permission' => 'menus.delete',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.menu-items.toggle',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:menus', 'can:menus.change_status'],
        'permission' => 'menus.change_status',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.menu-items.update',
        'methods' => ['PUT'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:menus', 'can:menus.edit'],
        'permission' => 'menus.edit',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.menus.index',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:menus', 'can:menus.view_any'],
        'permission' => 'menus.view_any',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.menus.items.store',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:menus', 'can:menus.create'],
        'permission' => 'menus.create',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.menus.link-check',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:menus', 'can:menus.view'],
        'permission' => 'menus.view',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.menus.reorder',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:menus', 'can:menus.edit'],
        'permission' => 'menus.edit',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.menus.show',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:menus', 'can:menus.view'],
        'permission' => 'menus.view',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.menus.update',
        'methods' => ['PUT'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:menus', 'can:menus.edit'],
        'permission' => 'menus.edit',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.pages.create',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:pages', 'can:pages.create'],
        'permission' => 'pages.create',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.pages.destroy',
        'methods' => ['DELETE'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:pages', 'can:pages.delete'],
        'permission' => 'pages.delete',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.pages.duplicate',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:pages', 'can:pages.create'],
        'permission' => 'pages.create',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.pages.edit',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:pages', 'can:pages.view'],
        'permission' => 'pages.view',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.pages.export',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:pages', 'can:pages.export'],
        'permission' => 'pages.export',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.pages.index',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:pages', 'can:pages.view_any'],
        'permission' => 'pages.view_any',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.pages.preview-link',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:pages', 'can:pages.view'],
        'permission' => 'pages.view',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.pages.publish',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:pages', 'can:pages.change_status'],
        'permission' => 'pages.change_status',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.pages.restore',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:pages', 'can:pages.restore'],
        'permission' => 'pages.restore',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.pages.revisions.index',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:pages', 'can:pages.view_logs'],
        'permission' => 'pages.view_logs',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.pages.revisions.revert',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:pages', 'can:pages.change_status'],
        'permission' => 'pages.change_status',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.pages.schedule',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:pages', 'can:pages.change_status'],
        'permission' => 'pages.change_status',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.pages.store',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:pages', 'can:pages.create'],
        'permission' => 'pages.create',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.pages.unpublish',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:pages', 'can:pages.change_status'],
        'permission' => 'pages.change_status',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.pages.update',
        'methods' => ['PUT'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:pages', 'can:pages.edit'],
        'permission' => 'pages.edit',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.section-items.destroy',
        'methods' => ['DELETE'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_sections', 'can:website_sections.edit'],
        'permission' => 'website_sections.edit',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.section-items.toggle',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_sections', 'can:website_sections.edit'],
        'permission' => 'website_sections.edit',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.section-items.update',
        'methods' => ['PUT'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_sections', 'can:website_sections.edit'],
        'permission' => 'website_sections.edit',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.sections.available',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_sections', 'can:website_sections.create'],
        'permission' => 'website_sections.create',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.sections.destroy',
        'methods' => ['DELETE'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_sections', 'can:website_sections.delete'],
        'permission' => 'website_sections.delete',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.sections.duplicate',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_sections', 'can:website_sections.create'],
        'permission' => 'website_sections.create',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.sections.edit',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_sections', 'can:website_sections.view'],
        'permission' => 'website_sections.view',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.sections.index',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_sections', 'can:website_sections.view_any'],
        'permission' => 'website_sections.view_any',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.sections.items.reorder',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_sections', 'can:website_sections.edit'],
        'permission' => 'website_sections.edit',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.sections.items.store',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_sections', 'can:website_sections.edit'],
        'permission' => 'website_sections.edit',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.sections.publish',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_sections', 'can:website_sections.change_status'],
        'permission' => 'website_sections.change_status',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.sections.reorder',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_sections', 'can:website_sections.edit'],
        'permission' => 'website_sections.edit',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.sections.revisions.index',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_sections', 'can:website_sections.view_logs'],
        'permission' => 'website_sections.view_logs',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.sections.revisions.revert',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_sections', 'can:website_sections.change_status'],
        'permission' => 'website_sections.change_status',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.sections.store',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_sections', 'can:website_sections.create'],
        'permission' => 'website_sections.create',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.sections.toggle',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_sections', 'can:website_sections.change_status'],
        'permission' => 'website_sections.change_status',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.sections.unpublish',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_sections', 'can:website_sections.change_status'],
        'permission' => 'website_sections.change_status',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.sections.update',
        'methods' => ['PUT'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_sections', 'can:website_sections.edit'],
        'permission' => 'website_sections.edit',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.seo.bulk-robots',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:seo', 'can:seo.edit'],
        'permission' => 'seo.edit',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.seo.edit',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:seo', 'can:seo.view'],
        'permission' => 'seo.view',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.seo.export',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:seo', 'can:seo.export'],
        'permission' => 'seo.export',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.seo.index',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:seo', 'can:seo.view_any'],
        'permission' => 'seo.view_any',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.seo.robots.preview',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:seo', 'can:seo.view'],
        'permission' => 'seo.view',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.seo.sitemap.history',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:seo', 'can:seo.view'],
        'permission' => 'seo.view',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.seo.sitemap.regenerate',
        'methods' => ['POST'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:seo', 'can:seo.edit', 'throttle:6,1,cms-sitemap-regenerate'],
        'permission' => 'seo.edit',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.seo.update',
        'methods' => ['PUT'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:seo', 'can:seo.edit'],
        'permission' => 'seo.edit',
        'panel' => 'admin',
        'state_changing' => true,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'admin.website.statistics.index',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'auth', 'active', 'panel:admin', 'module:website_sections', 'can:website_sections.view_any'],
        'permission' => 'website_sections.view_any',
        'panel' => 'admin',
        'state_changing' => false,
        'rationale' => null,
        'owner_phase' => 3,
    ],
    [
        'route' => 'site.home',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'site', 'site.preview', 'site.cache'],
        'permission' => null,
        'panel' => 'public',
        'state_changing' => false,
        'rationale' => 'The public home page (phase-03 §7.6): the published output of the CMS, not a module\'s UI, so it carries no module: or can: gate (INV-15, D26). `site` closes it for maintenance or when the public site is switched off; only published snapshots render, and a draft is reachable only through the authorised preview routes.',
        'owner_phase' => 3,
    ],
    [
        'route' => 'site.page',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'site', 'site.preview', 'site.cache'],
        'permission' => null,
        'panel' => 'public',
        'state_changing' => false,
        'rationale' => 'A published CMS page at /{slug} (phase-03 §7.6), loaded after every other route file. Public by definition (INV-15, D26): only a published, non-trashed page resolves and anything else is a 404; `site` closes it for maintenance or a disabled public site; a draft is reachable only through the authorised preview routes.',
        'owner_phase' => 3,
    ],
    [
        'route' => 'site.preview.page',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'site', 'site.preview'],
        'permission' => null,
        'panel' => 'public',
        'state_changing' => false,
        'rationale' => 'Authorised inside Site\\PreviewController, not by route middleware (phase-03 §6.12, §9): a valid temporary signature (a reviewer with no account), or a session in good standing holding pages.view. A bad signature is 403, none is 404, and a missing id answers the same as a forbidden one. A route-level can: would refuse the signed-link reviewer the contract requires.',
        'owner_phase' => 3,
    ],
    [
        'route' => 'site.preview.section',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'site', 'site.preview'],
        'permission' => null,
        'panel' => 'public',
        'state_changing' => false,
        'rationale' => 'Authorised inside Site\\PreviewController, not by route middleware (phase-03 §6.12, §9): a valid temporary signature, or a session in good standing holding website_sections.view. A bad signature is 403, none is 404, and a missing id answers the same as a forbidden one.',
        'owner_phase' => 3,
    ],
    [
        'route' => 'site.robots',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web'],
        'permission' => null,
        'panel' => 'public',
        'state_changing' => false,
        'rationale' => 'robots.txt is a crawler file and must stay readable while the site is closed, so it carries neither can: nor the `site` gate ([D-W3-13]). It holds no private data: a locked-down site (not indexable, in maintenance or switched off) answers "Disallow: /" with no sitemap line (phase-03 §6.5, FT-47).',
        'owner_phase' => 3,
    ],
    [
        'route' => 'site.sitemap',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'site', 'site.cache'],
        'permission' => null,
        'panel' => 'public',
        'state_changing' => false,
        'rationale' => 'sitemap.xml is a crawler file (phase-03 §6.5, §105): it lists only published, indexable, included public URLs, is empty when the site is not indexable and a 404 when seo.sitemap_enabled is off. Built from seo.canonical_base_url / config(app.url), never the request Host (review round 2).',
        'owner_phase' => 3,
    ],
    [
        'route' => 'site.sitemap.chunk',
        'methods' => ['GET', 'HEAD'],
        'middleware' => ['web', 'site', 'site.cache'],
        'permission' => null,
        'panel' => 'public',
        'state_changing' => false,
        'rationale' => 'A sitemap chunk file (phase-03 §6.5): exists only when the URL set exceeds 40 000 entries, otherwise a 404 answered from the cached chunk count without rebuilding. Same content rules as sitemap.xml.',
        'owner_phase' => 3,
    ],

];
