<?php

declare(strict_types=1);

use App\Enums\Cms\ContentStatus;
use App\Enums\Cms\MenuLocation;
use App\Enums\Cms\SectionPlacement;
use App\Models\Cms\CtaBlock;
use App\Models\Cms\MediaAsset;
use App\Models\Cms\Menu;
use App\Models\Cms\Page;
use App\Models\Cms\WebsiteSection;

/*
|--------------------------------------------------------------------------
| Screen manifest (D60; phase-24-25 §6.1, §13.2; build-order E4)
|--------------------------------------------------------------------------
|
| One row per GET route a phase ships — the data provider of every screen sweep: query budgets (PRF-01),
| responsive (RSP-*), accessibility (A11Y-*) and IDOR (ISO-*). Phase 24's `audit:manifest --check` fails on
| a GET route with no row and on a row whose route no longer exists.
|
| Append-only per phase: each phase adds its own rows, under its own banner, as part of its definition of
| done, and never edits another phase's.
|
| Row shape:
|   'route'         route name
|   'panel'         admin | collaborator | student | teacher | client | public
|   'kind'          index | show | form | board | calendar | wizard | print | public | export | dashboard | statement
|   'params'        fn (?object $fixture = null): array — the route parameters (and query) of one real
|                   instance. Phase 3's closures read the first matching row, so the fixture must hold at
|                   least one row of each model they name; the Phase 3 seeder provides every one except a
|                   media asset.
|   'permissions'   what the viewer must hold (the route's `can:`; for a preview, the session alternative)
|   'module'        the module slug of the route's `module:` gate, null for the public site (INV-15)
|   'owner_phase'   the phase that ships the screen
|   'query_budget'  PRF-01's ceiling; the kind's default unless a 'budget_reason' says otherwise (Phase 3's
|                   rows were measured warm, as a Super Admin, on the seeded site: every one is within it)
|   'responsive'    in the responsive sweep
|   'a11y'          in the accessibility sweep
|   'idor'          ['owner' => the ownership column] or ['owner' => null] for a screen with no owner scope
|   'response'      html | json | csv | text | xml — what a GET answers (sweeps that parse HTML skip the rest)
|   'expect'        (optional) the status the sweep should expect on the standard fixture when it is not 200
|
*/

$first = static fn (string $model, ?Closure $scope = null): int => (int) $model::query()
    ->when($scope !== null, $scope)
    ->orderBy('id')
    ->value('id');

return [

    /*
    |----------------------------------------------------------------------
    | Phase 3 — public website CMS (35 GET routes: 28 admin.website.*, 7 site.*)
    |----------------------------------------------------------------------
    | Staff screens behind the admin panel: no owner scope, so no IDOR owner column (phase-03 §9 — the CMS
    | is visible to whoever holds the permission). tests/Feature/Cms/Http/CmsManifestTest keeps these rows
    | equal to the live route table and proves every params closure resolves to a screen that answers.
    */

    [
        'route' => 'admin.website.index',
        'panel' => 'admin',
        'kind' => 'dashboard',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['website_sections.view_any'],
        'module' => 'website_sections',
        'owner_phase' => 3,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.sections.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => ['placement' => SectionPlacement::Home->value],
        'permissions' => ['website_sections.view_any'],
        'module' => 'website_sections',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.sections.available',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => ['placement' => SectionPlacement::Home->value],
        'permissions' => ['website_sections.create'],
        'module' => 'website_sections',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.sections.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => ['section' => $first(WebsiteSection::class, static fn ($q) => $q->where('section_key', 'hero'))],
        'permissions' => ['website_sections.view'],
        'module' => 'website_sections',
        'owner_phase' => 3,
        'query_budget' => 15,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.sections.revisions.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => ['section' => $first(WebsiteSection::class, static fn ($q) => $q->where('section_key', 'hero'))],
        'permissions' => ['website_sections.view_logs'],
        'module' => 'website_sections',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.statistics.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['website_sections.view_any'],
        'module' => 'website_sections',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.menus.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['menus.view_any'],
        'module' => 'menus',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.menus.show',
        'panel' => 'admin',
        'kind' => 'board',
        'params' => static fn (?object $fixture = null): array => ['menu' => $first(Menu::class, static fn ($q) => $q->where('location', MenuLocation::Header->value))],
        'permissions' => ['menus.view'],
        'module' => 'menus',
        'owner_phase' => 3,
        'query_budget' => 10,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.menus.link-check',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => ['menu' => $first(Menu::class, static fn ($q) => $q->where('location', MenuLocation::Header->value))],
        'permissions' => ['menus.view'],
        'module' => 'menus',
        'owner_phase' => 3,
        'query_budget' => 20,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.pages.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['pages.view_any'],
        'module' => 'pages',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.pages.create',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['pages.create'],
        'module' => 'pages',
        'owner_phase' => 3,
        'query_budget' => 15,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.pages.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => ['page' => $first(Page::class, static fn ($q) => $q->where('slug', 'privacy-policy'))],
        'permissions' => ['pages.view'],
        'module' => 'pages',
        'owner_phase' => 3,
        'query_budget' => 15,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.pages.revisions.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => ['page' => $first(Page::class, static fn ($q) => $q->where('slug', 'privacy-policy'))],
        'permissions' => ['pages.view_logs'],
        'module' => 'pages',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.pages.preview-link',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => ['page' => $first(Page::class, static fn ($q) => $q->where('slug', 'privacy-policy'))],
        'permissions' => ['pages.view'],
        'module' => 'pages',
        'owner_phase' => 3,
        'query_budget' => 20,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'json',
    ],
    [
        'route' => 'admin.website.pages.export',
        'panel' => 'admin',
        'kind' => 'export',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['pages.export'],
        'module' => 'pages',
        'owner_phase' => 3,
        'query_budget' => 7,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'csv',
    ],
    [
        'route' => 'admin.website.cta-blocks.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['website_cta_blocks.view_any'],
        'module' => 'website_cta_blocks',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.cta-blocks.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => ['ctaBlock' => $first(CtaBlock::class)],
        'permissions' => ['website_cta_blocks.view'],
        'module' => 'website_cta_blocks',
        'owner_phase' => 3,
        'query_budget' => 15,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.cta-blocks.usage',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => ['ctaBlock' => $first(CtaBlock::class)],
        'permissions' => ['website_cta_blocks.view'],
        'module' => 'website_cta_blocks',
        'owner_phase' => 3,
        'query_budget' => 20,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.faqs.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['faqs.view_any'],
        'module' => 'faqs',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.faq-categories.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['faq_categories.view_any'],
        'module' => 'faq_categories',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.seo.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['seo.view_any'],
        'module' => 'seo',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.seo.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => ['target' => 'route:site.home'],
        'permissions' => ['seo.view'],
        'module' => 'seo',
        'owner_phase' => 3,
        'query_budget' => 15,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.seo.sitemap.history',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['seo.view'],
        'module' => 'seo',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.seo.robots.preview',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['seo.view'],
        'module' => 'seo',
        'owner_phase' => 3,
        'query_budget' => 20,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.seo.export',
        'panel' => 'admin',
        'kind' => 'export',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['seo.export'],
        'module' => 'seo',
        'owner_phase' => 3,
        'query_budget' => 7,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'csv',
    ],
    [
        'route' => 'admin.website.media.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['website_media.view_any'],
        'module' => 'website_media',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.media.show',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => ['asset' => $first(MediaAsset::class)],
        'permissions' => ['website_media.view'],
        'module' => 'website_media',
        'owner_phase' => 3,
        'query_budget' => 20,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.media.usage',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => ['asset' => $first(MediaAsset::class)],
        'permissions' => ['website_media.view'],
        'module' => 'website_media',
        'owner_phase' => 3,
        'query_budget' => 20,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    // Phase 3 — the public site. PRF-01's public default is 8 queries cold and 1 warm (the cached response).
    [
        'route' => 'site.home',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 3,
        'query_budget' => 8,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'site.page',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => [
            'slug' => (string) Page::query()->where('status', ContentStatus::Published->value)->where('slug', 'privacy-policy')->value('slug'),
        ],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 3,
        'query_budget' => 8,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'site.preview.page',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => ['page' => $first(Page::class, static fn ($q) => $q->where('slug', 'privacy-policy'))],
        'permissions' => ['pages.view'],
        'module' => null,
        'owner_phase' => 3,
        'query_budget' => 24,
        'budget_reason' => 'A preview is never cached and resolves the draft page, its sections, the account behind the session and its permissions on every request (§6.12): 21 queries measured on the seeded privacy page (review round 2), so it is budgeted above a show screen, not as a cached public page.',
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'site.preview.section',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => ['section' => $first(WebsiteSection::class, static fn ($q) => $q->where('section_key', 'hero'))],
        'permissions' => ['website_sections.view'],
        'module' => null,
        'owner_phase' => 3,
        'query_budget' => 20,
        'budget_reason' => 'A preview is never cached and resolves the draft, the account behind the session and its permissions on every request (§6.12), so it is budgeted as a show screen, not as a cached public page.',
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'site.robots',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 3,
        'query_budget' => 8,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'text',
    ],
    [
        'route' => 'site.sitemap',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 3,
        'query_budget' => 8,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'xml',
    ],
    [
        'route' => 'site.sitemap.chunk',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => ['index' => 1],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 3,
        'query_budget' => 8,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'xml',
        'expect' => 404,
    ],

];
