<?php

declare(strict_types=1);

use App\Enums\Cms\ContentStatus;
use App\Enums\Cms\MenuLocation;
use App\Enums\Cms\SectionPlacement;
use App\Models\Cms\CtaBlock;
use App\Models\Cms\MediaAsset;
use App\Models\Cms\Menu;
use App\Models\Cms\Page;
use App\Models\Cms\WebsiteSection;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Screen manifest (D60; phase-24-25 §6.1, §13.2; build-order E4)
|--------------------------------------------------------------------------
|
| One row per GET route a phase ships — the data provider of every screen sweep: query budgets (PRF-01),
| responsive (RSP-*), accessibility (A11Y-*) and IDOR (ISO-*). Phase 24's `audit:manifest --check` fails on
| a GET route with no row and on a row whose route no longer exists.
|
| Append-only per phase: each phase adds its own rows, under its own banner, as part of its definition of
| done, and never edits another phase's.
|
| Row shape:
|   'route'         route name
|   'panel'         admin | collaborator | student | teacher | client | public
|   'kind'          index | show | form | board | calendar | wizard | print | public | export | dashboard | statement
|   'params'        fn (?object $fixture = null): array — the route parameters (and query) of one real
|                   instance. Phase 3's closures read the first matching row, so the fixture must hold at
|                   least one row of each model they name; the Phase 3 seeder provides every one except a
|                   media asset.
|   'permissions'   what the viewer must hold (the route's `can:`; for a preview, the session alternative)
|   'module'        the module slug of the route's `module:` gate, null for the public site (INV-15)
|   'owner_phase'   the phase that ships the screen
|   'query_budget'  PRF-01's ceiling; the kind's default unless a 'budget_reason' says otherwise (Phase 3's
|                   rows were measured warm, as a Super Admin, on the seeded site: every one is within it)
|   'responsive'    in the responsive sweep
|   'a11y'          in the accessibility sweep
|   'idor'          ['owner' => the ownership column] or ['owner' => null] for a screen with no owner scope
|   'response'      html | json | csv | text | xml — what a GET answers (sweeps that parse HTML skip the rest)
|   'expect'        (optional) the status the sweep should expect on the standard fixture when it is not 200
|
*/

$first = static fn (string $model, ?Closure $scope = null): int => (int) $model::query()
    ->when($scope !== null, $scope)
    ->orderBy('id')
    ->value('id');

return [

    /*
    |----------------------------------------------------------------------
    | Phase 3 — public website CMS (35 GET routes: 28 admin.website.*, 7 site.*)
    |----------------------------------------------------------------------
    | Staff screens behind the admin panel: no owner scope, so no IDOR owner column (phase-03 §9 — the CMS
    | is visible to whoever holds the permission). tests/Feature/Cms/Http/CmsManifestTest keeps these rows
    | equal to the live route table and proves every params closure resolves to a screen that answers.
    */

    [
        'route' => 'admin.website.index',
        'panel' => 'admin',
        'kind' => 'dashboard',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['website_sections.view_any'],
        'module' => 'website_sections',
        'owner_phase' => 3,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.sections.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => ['placement' => SectionPlacement::Home->value],
        'permissions' => ['website_sections.view_any'],
        'module' => 'website_sections',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.sections.available',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => ['placement' => SectionPlacement::Home->value],
        'permissions' => ['website_sections.create'],
        'module' => 'website_sections',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.sections.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => ['section' => $first(WebsiteSection::class, static fn ($q) => $q->where('section_key', 'hero'))],
        'permissions' => ['website_sections.view'],
        'module' => 'website_sections',
        'owner_phase' => 3,
        'query_budget' => 15,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.sections.revisions.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => ['section' => $first(WebsiteSection::class, static fn ($q) => $q->where('section_key', 'hero'))],
        'permissions' => ['website_sections.view_logs'],
        'module' => 'website_sections',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.statistics.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['website_sections.view_any'],
        'module' => 'website_sections',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.menus.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['menus.view_any'],
        'module' => 'menus',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.menus.show',
        'panel' => 'admin',
        'kind' => 'board',
        'params' => static fn (?object $fixture = null): array => ['menu' => $first(Menu::class, static fn ($q) => $q->where('location', MenuLocation::Header->value))],
        'permissions' => ['menus.view'],
        'module' => 'menus',
        'owner_phase' => 3,
        'query_budget' => 10,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.menus.link-check',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => ['menu' => $first(Menu::class, static fn ($q) => $q->where('location', MenuLocation::Header->value))],
        'permissions' => ['menus.view'],
        'module' => 'menus',
        'owner_phase' => 3,
        'query_budget' => 20,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.pages.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['pages.view_any'],
        'module' => 'pages',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.pages.create',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['pages.create'],
        'module' => 'pages',
        'owner_phase' => 3,
        'query_budget' => 15,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.pages.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => ['page' => $first(Page::class, static fn ($q) => $q->where('slug', 'privacy-policy'))],
        'permissions' => ['pages.view'],
        'module' => 'pages',
        'owner_phase' => 3,
        'query_budget' => 15,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.pages.revisions.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => ['page' => $first(Page::class, static fn ($q) => $q->where('slug', 'privacy-policy'))],
        'permissions' => ['pages.view_logs'],
        'module' => 'pages',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.pages.preview-link',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => ['page' => $first(Page::class, static fn ($q) => $q->where('slug', 'privacy-policy'))],
        'permissions' => ['pages.view'],
        'module' => 'pages',
        'owner_phase' => 3,
        'query_budget' => 20,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'json',
    ],
    [
        'route' => 'admin.website.pages.export',
        'panel' => 'admin',
        'kind' => 'export',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['pages.export'],
        'module' => 'pages',
        'owner_phase' => 3,
        'query_budget' => 7,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'csv',
    ],
    [
        'route' => 'admin.website.cta-blocks.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['website_cta_blocks.view_any'],
        'module' => 'website_cta_blocks',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.cta-blocks.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => ['ctaBlock' => $first(CtaBlock::class)],
        'permissions' => ['website_cta_blocks.view'],
        'module' => 'website_cta_blocks',
        'owner_phase' => 3,
        'query_budget' => 15,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.cta-blocks.usage',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => ['ctaBlock' => $first(CtaBlock::class)],
        'permissions' => ['website_cta_blocks.view'],
        'module' => 'website_cta_blocks',
        'owner_phase' => 3,
        'query_budget' => 20,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.faqs.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['faqs.view_any'],
        'module' => 'faqs',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.faq-categories.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['faq_categories.view_any'],
        'module' => 'faq_categories',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.seo.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['seo.view_any'],
        'module' => 'seo',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.seo.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => ['target' => 'route:site.home'],
        'permissions' => ['seo.view'],
        'module' => 'seo',
        'owner_phase' => 3,
        'query_budget' => 15,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.seo.sitemap.history',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['seo.view'],
        'module' => 'seo',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.seo.robots.preview',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['seo.view'],
        'module' => 'seo',
        'owner_phase' => 3,
        'query_budget' => 20,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.seo.export',
        'panel' => 'admin',
        'kind' => 'export',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['seo.export'],
        'module' => 'seo',
        'owner_phase' => 3,
        'query_budget' => 7,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'csv',
    ],
    [
        'route' => 'admin.website.media.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['website_media.view_any'],
        'module' => 'website_media',
        'owner_phase' => 3,
        'query_budget' => 12,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.media.show',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => ['asset' => $first(MediaAsset::class)],
        'permissions' => ['website_media.view'],
        'module' => 'website_media',
        'owner_phase' => 3,
        'query_budget' => 20,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.website.media.usage',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => ['asset' => $first(MediaAsset::class)],
        'permissions' => ['website_media.view'],
        'module' => 'website_media',
        'owner_phase' => 3,
        'query_budget' => 20,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    // Phase 3 — the public site. PRF-01's public default is 8 queries cold and 1 warm (the cached response).
    [
        'route' => 'site.home',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 3,
        'query_budget' => 8,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'site.page',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => [
            'slug' => (string) Page::query()->where('status', ContentStatus::Published->value)->where('slug', 'privacy-policy')->value('slug'),
        ],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 3,
        'query_budget' => 8,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'site.preview.page',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => ['page' => $first(Page::class, static fn ($q) => $q->where('slug', 'privacy-policy'))],
        'permissions' => ['pages.view'],
        'module' => null,
        'owner_phase' => 3,
        'query_budget' => 24,
        'budget_reason' => 'A preview is never cached and resolves the draft page, its sections, the account behind the session and its permissions on every request (§6.12): 21 queries measured on the seeded privacy page (review round 2), so it is budgeted above a show screen, not as a cached public page.',
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'site.preview.section',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => ['section' => $first(WebsiteSection::class, static fn ($q) => $q->where('section_key', 'hero'))],
        'permissions' => ['website_sections.view'],
        'module' => null,
        'owner_phase' => 3,
        'query_budget' => 20,
        'budget_reason' => 'A preview is never cached and resolves the draft, the account behind the session and its permissions on every request (§6.12), so it is budgeted as a show screen, not as a cached public page.',
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'site.robots',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 3,
        'query_budget' => 8,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'text',
    ],
    [
        'route' => 'site.sitemap',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 3,
        'query_budget' => 8,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'xml',
    ],
    [
        'route' => 'site.sitemap.chunk',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => ['index' => 1],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 3,
        'query_budget' => 8,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'xml',
        'expect' => 404,
    ],

    /*
    |----------------------------------------------------------------------
    | Phase 4 — services, portfolio, team, social proof, blog, careers, inquiries (76 GET routes)
    |----------------------------------------------------------------------
    | Generated from the live route table. Every params closure resolves against the fixture
    | MarketingHttpFixtures builds, so each row names a row that exists. Admin screens carry no owner
    | scope (the catalogue is visible to whoever holds the permission), so idor owner is null.
    */
    [
        'route' => 'admin.blog-categories.create',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['blog_categories.create'],
        'module' => 'blog_categories',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 302,
    ],
    [
        'route' => 'admin.blog-categories.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [
            'term' => (int) DB::table('blog_categories')->orderBy('id')->value('id'),
        ],
        'permissions' => ['blog_categories.edit'],
        'module' => 'blog_categories',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.blog-categories.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['blog_categories.view_any'],
        'module' => 'blog_categories',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.blog-categories.show',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => [
            'term' => (int) DB::table('blog_categories')->orderBy('id')->value('id'),
        ],
        'permissions' => ['blog_categories.view'],
        'module' => 'blog_categories',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 302,
    ],
    [
        'route' => 'admin.blog-posts.calendar',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['blog_posts.view_any'],
        'module' => 'blog_posts',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.blog-posts.create',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['blog_posts.create'],
        'module' => 'blog_posts',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.blog-posts.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [
            'post' => (int) DB::table('blog_posts')->orderBy('id')->value('id'),
        ],
        'permissions' => ['blog_posts.edit'],
        'module' => 'blog_posts',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.blog-posts.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['blog_posts.view_any'],
        'module' => 'blog_posts',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.blog-posts.preview-link',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [
            'post' => (int) DB::table('blog_posts')->orderBy('id')->value('id'),
        ],
        'permissions' => ['blog_posts.view'],
        'module' => 'blog_posts',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 302,
    ],
    [
        'route' => 'admin.blog-posts.show',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => [
            'post' => (int) DB::table('blog_posts')->orderBy('id')->value('id'),
        ],
        'permissions' => ['blog_posts.view'],
        'module' => 'blog_posts',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 302,
    ],
    [
        'route' => 'admin.blog-posts.stats',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [
            'post' => (int) DB::table('blog_posts')->orderBy('id')->value('id'),
        ],
        'permissions' => ['blog_posts.view_reports'],
        'module' => 'blog_posts',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.blog-tags.create',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['blog_tags.create'],
        'module' => 'blog_tags',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 302,
    ],
    [
        'route' => 'admin.blog-tags.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [
            'term' => (int) DB::table('blog_tags')->orderBy('id')->value('id'),
        ],
        'permissions' => ['blog_tags.edit'],
        'module' => 'blog_tags',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 302,
    ],
    [
        'route' => 'admin.blog-tags.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['blog_tags.view_any'],
        'module' => 'blog_tags',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.blog-tags.show',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => [
            'term' => (int) DB::table('blog_tags')->orderBy('id')->value('id'),
        ],
        'permissions' => ['blog_tags.view'],
        'module' => 'blog_tags',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 302,
    ],
    [
        'route' => 'admin.contact-inquiries.export',
        'panel' => 'admin',
        'kind' => 'export',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['contact_inquiries.export'],
        'module' => 'contact_inquiries',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'csv',
    ],
    [
        'route' => 'admin.contact-inquiries.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['contact_inquiries.view'],
        'module' => 'contact_inquiries',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.contact-inquiries.show',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => [
            'inquiry' => (int) DB::table('contact_inquiries')->orderBy('id')->value('id'),
        ],
        'permissions' => ['contact_inquiries.view'],
        'module' => 'contact_inquiries',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.job-applications.cv',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [
            'application' => (int) DB::table('job_applications')->orderBy('id')->value('id'),
        ],
        'permissions' => ['job_applications.download'],
        'module' => 'job_applications',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.job-applications.export',
        'panel' => 'admin',
        'kind' => 'export',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['job_applications.export'],
        'module' => 'job_applications',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'csv',
    ],
    [
        'route' => 'admin.job-applications.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['job_applications.view'],
        'module' => 'job_applications',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.job-applications.show',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => [
            'application' => (int) DB::table('job_applications')->orderBy('id')->value('id'),
        ],
        'permissions' => ['job_applications.view'],
        'module' => 'job_applications',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.jobs.create',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['jobs.create'],
        'module' => 'jobs',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.jobs.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [
            'job' => (int) DB::table('job_openings')->orderBy('id')->value('id'),
        ],
        'permissions' => ['jobs.edit'],
        'module' => 'jobs',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.jobs.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['jobs.view_any'],
        'module' => 'jobs',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.jobs.show',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => [
            'job' => (int) DB::table('job_openings')->orderBy('id')->value('id'),
        ],
        'permissions' => ['jobs.view'],
        'module' => 'jobs',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 302,
    ],
    [
        'route' => 'admin.portfolio-categories.create',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['portfolio_categories.create'],
        'module' => 'portfolio_categories',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 302,
    ],
    [
        'route' => 'admin.portfolio-categories.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [
            'term' => (int) DB::table('portfolio_categories')->orderBy('id')->value('id'),
        ],
        'permissions' => ['portfolio_categories.edit'],
        'module' => 'portfolio_categories',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.portfolio-categories.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['portfolio_categories.view_any'],
        'module' => 'portfolio_categories',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.portfolio-categories.show',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => [
            'term' => (int) DB::table('portfolio_categories')->orderBy('id')->value('id'),
        ],
        'permissions' => ['portfolio_categories.view'],
        'module' => 'portfolio_categories',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 302,
    ],
    [
        'route' => 'admin.portfolio.create',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['portfolio.create'],
        'module' => 'portfolio',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.portfolio.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [
            'item' => (int) DB::table('portfolio_items')->orderBy('id')->value('id'),
        ],
        'permissions' => ['portfolio.edit'],
        'module' => 'portfolio',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.portfolio.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['portfolio.view_any'],
        'module' => 'portfolio',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.portfolio.show',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => [
            'item' => (int) DB::table('portfolio_items')->orderBy('id')->value('id'),
        ],
        'permissions' => ['portfolio.view'],
        'module' => 'portfolio',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 302,
    ],
    [
        'route' => 'admin.service-categories.create',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['service_categories.create'],
        'module' => 'service_categories',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 302,
    ],
    [
        'route' => 'admin.service-categories.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [
            'term' => (int) DB::table('service_categories')->orderBy('id')->value('id'),
        ],
        'permissions' => ['service_categories.edit'],
        'module' => 'service_categories',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.service-categories.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['service_categories.view_any'],
        'module' => 'service_categories',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.service-categories.show',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => [
            'term' => (int) DB::table('service_categories')->orderBy('id')->value('id'),
        ],
        'permissions' => ['service_categories.view'],
        'module' => 'service_categories',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 302,
    ],
    [
        'route' => 'admin.services.create',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['services.create'],
        'module' => 'services',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.services.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [
            'service' => (int) DB::table('services')->orderBy('id')->value('id'),
        ],
        'permissions' => ['services.edit'],
        'module' => 'services',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.services.export',
        'panel' => 'admin',
        'kind' => 'export',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['services.export'],
        'module' => 'services',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'csv',
    ],
    [
        'route' => 'admin.services.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['services.view_any'],
        'module' => 'services',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.services.show',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => [
            'service' => (int) DB::table('services')->orderBy('id')->value('id'),
        ],
        'permissions' => ['services.view'],
        'module' => 'services',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 302,
    ],
    [
        'route' => 'admin.student-reviews.create',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['student_reviews.create'],
        'module' => 'student_reviews',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.student-reviews.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [
            'review' => (int) DB::table('student_reviews')->orderBy('id')->value('id'),
        ],
        'permissions' => ['student_reviews.edit'],
        'module' => 'student_reviews',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.student-reviews.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['student_reviews.view_any'],
        'module' => 'student_reviews',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.student-reviews.show',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => [
            'review' => (int) DB::table('student_reviews')->orderBy('id')->value('id'),
        ],
        'permissions' => ['student_reviews.view'],
        'module' => 'student_reviews',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 302,
    ],
    [
        'route' => 'admin.success-stories.create',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['success_stories.create'],
        'module' => 'success_stories',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.success-stories.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [
            'story' => (int) DB::table('success_stories')->orderBy('id')->value('id'),
        ],
        'permissions' => ['success_stories.edit'],
        'module' => 'success_stories',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.success-stories.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['success_stories.view_any'],
        'module' => 'success_stories',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.success-stories.show',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => [
            'story' => (int) DB::table('success_stories')->orderBy('id')->value('id'),
        ],
        'permissions' => ['success_stories.view'],
        'module' => 'success_stories',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 302,
    ],
    [
        'route' => 'admin.team.create',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['team.create'],
        'module' => 'team',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.team.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [
            'member' => (int) DB::table('team_members')->orderBy('id')->value('id'),
        ],
        'permissions' => ['team.edit'],
        'module' => 'team',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.team.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['team.view_any'],
        'module' => 'team',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.team.show',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => [
            'member' => (int) DB::table('team_members')->orderBy('id')->value('id'),
        ],
        'permissions' => ['team.view'],
        'module' => 'team',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 302,
    ],
    [
        'route' => 'admin.technologies.create',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['technologies.create'],
        'module' => 'technologies',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 302,
    ],
    [
        'route' => 'admin.technologies.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [
            'term' => (int) DB::table('technologies')->orderBy('id')->value('id'),
        ],
        'permissions' => ['technologies.edit'],
        'module' => 'technologies',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 302,
    ],
    [
        'route' => 'admin.technologies.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['technologies.view_any'],
        'module' => 'technologies',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.technologies.show',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => [
            'term' => (int) DB::table('technologies')->orderBy('id')->value('id'),
        ],
        'permissions' => ['technologies.view'],
        'module' => 'technologies',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 302,
    ],
    [
        'route' => 'admin.testimonials.create',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['testimonials.create'],
        'module' => 'testimonials',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.testimonials.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [
            'testimonial' => (int) DB::table('testimonials')->orderBy('id')->value('id'),
        ],
        'permissions' => ['testimonials.edit'],
        'module' => 'testimonials',
        'owner_phase' => 4,
        'query_budget' => 30,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.testimonials.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['testimonials.view_any'],
        'module' => 'testimonials',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'admin.testimonials.show',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => [
            'testimonial' => (int) DB::table('testimonials')->orderBy('id')->value('id'),
        ],
        'permissions' => ['testimonials.view'],
        'module' => 'testimonials',
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 302,
    ],
    [
        'route' => 'site.blog.category',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => [
            'blogCategory' => (string) DB::table('blog_categories')->orderBy('id')->value('slug'),
        ],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'site.blog.index',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'site.blog.preview',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => [
            'blogPost' => (string) DB::table('blog_posts')->whereIn('status', ['published', 'open', 'approved'])->orderBy('id')->value('slug'),
        ],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
        'expect' => 404,
    ],
    [
        'route' => 'site.blog.show',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => [
            'blogPost' => (string) DB::table('blog_posts')->whereIn('status', ['published', 'open', 'approved'])->orderBy('id')->value('slug'),
        ],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'site.blog.tag',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => [
            'blogTag' => (string) DB::table('blog_tags')->orderBy('id')->value('slug'),
        ],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'site.careers.index',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'site.careers.show',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => [
            'jobOpening' => (string) DB::table('job_openings')->whereIn('status', ['published', 'open', 'approved'])->orderBy('id')->value('slug'),
        ],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'site.contact.index',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'site.portfolio.index',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'site.portfolio.show',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => [
            'portfolioItem' => (string) DB::table('portfolio_items')->whereIn('status', ['published', 'open', 'approved'])->orderBy('id')->value('slug'),
        ],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'site.services.index',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'site.services.show',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => [
            'service' => (string) DB::table('services')->whereIn('status', ['published', 'open', 'approved'])->orderBy('id')->value('slug'),
        ],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],
    [
        'route' => 'site.team.index',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 4,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    /*
    |----------------------------------------------------------------------
    | Phase 13 - software-house finance (33 GET routes)
    |----------------------------------------------------------------------
    | Staff screens behind the admin panel have no owner scope, so no IDOR owner column: a finance
    | register is visible to whoever holds the permission (phase-13 sec 9). The public invoice row is
    | the exception and carries `client_id`, because that link is one client's own document.
    |
    | The print and export rows are out of the responsive sweep on purpose - a print stylesheet has no
    | breakpoints to test - and the CSV rows are out of the accessibility sweep, which parses HTML.
    */

    [
        'route' => 'admin.expenses.approvals',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['expenses.approve'],
        'module' => 'expenses',
        'owner_phase' => 13,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.expenses.create',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['expenses.create'],
        'module' => 'expenses',
        'owner_phase' => 13,
        'query_budget' => 20,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.expenses.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => ['expense' => $first(\App\Models\Finance\Expense::class)],
        'permissions' => ['expenses.edit'],
        'module' => 'expenses',
        'owner_phase' => 13,
        'query_budget' => 20,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.expenses.export',
        'panel' => 'admin',
        'kind' => 'export',
        'params' => static fn (?object $fixture = null): array => ['format' => 'csv'],
        'permissions' => ['expenses.export', 'expenses.view_financial'],
        'module' => 'expenses',
        'owner_phase' => 13,
        'query_budget' => 20,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'csv',
    ],

    [
        'route' => 'admin.expenses.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['expenses.view_any'],
        'module' => 'expenses',
        'owner_phase' => 13,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.expenses.receipt',
        'panel' => 'admin',
        'kind' => 'export',
        'params' => static fn (?object $fixture = null): array => ['expense' => $first(\App\Models\Finance\Expense::class)],
        'permissions' => ['expenses.download'],
        'module' => 'expenses',
        'owner_phase' => 13,
        'query_budget' => 20,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.expenses.show',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => ['expense' => $first(\App\Models\Finance\Expense::class)],
        'permissions' => ['expenses.view'],
        'module' => 'expenses',
        'owner_phase' => 13,
        'query_budget' => 20,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.finance-categories.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['finance_categories.view_any'],
        'module' => 'finance_categories',
        'owner_phase' => 13,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.income.create',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['income.create'],
        'module' => 'income',
        'owner_phase' => 13,
        'query_budget' => 20,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.income.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => ['income' => $first(\App\Models\Finance\Income::class)],
        'permissions' => ['income.edit'],
        'module' => 'income',
        'owner_phase' => 13,
        'query_budget' => 20,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.income.export',
        'panel' => 'admin',
        'kind' => 'export',
        'params' => static fn (?object $fixture = null): array => ['format' => 'csv'],
        'permissions' => ['income.export', 'income.view_financial'],
        'module' => 'income',
        'owner_phase' => 13,
        'query_budget' => 20,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'csv',
    ],

    [
        'route' => 'admin.income.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['income.view_any'],
        'module' => 'income',
        'owner_phase' => 13,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.income.receipt',
        'panel' => 'admin',
        'kind' => 'export',
        'params' => static fn (?object $fixture = null): array => ['income' => $first(\App\Models\Finance\Income::class)],
        'permissions' => ['income.download'],
        'module' => 'income',
        'owner_phase' => 13,
        'query_budget' => 20,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.income.show',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => ['income' => $first(\App\Models\Finance\Income::class)],
        'permissions' => ['income.view'],
        'module' => 'income',
        'owner_phase' => 13,
        'query_budget' => 20,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.invoices.create',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['invoices.create'],
        'module' => 'invoices',
        'owner_phase' => 13,
        'query_budget' => 20,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.invoices.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => ['invoice' => $first(\App\Models\Finance\Invoice::class)],
        'permissions' => ['invoices.edit'],
        'module' => 'invoices',
        'owner_phase' => 13,
        'query_budget' => 20,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.invoices.export',
        'panel' => 'admin',
        'kind' => 'export',
        'params' => static fn (?object $fixture = null): array => ['format' => 'csv'],
        'permissions' => ['invoices.export', 'invoices.view_financial'],
        'module' => 'invoices',
        'owner_phase' => 13,
        'query_budget' => 20,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'csv',
    ],

    [
        'route' => 'admin.invoices.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['invoices.view_any'],
        'module' => 'invoices',
        'owner_phase' => 13,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.invoices.print',
        'panel' => 'admin',
        'kind' => 'print',
        'params' => static fn (?object $fixture = null): array => ['invoice' => $first(\App\Models\Finance\Invoice::class)],
        'permissions' => ['invoices.print', 'invoices.view_financial'],
        'module' => 'invoices',
        'owner_phase' => 13,
        'query_budget' => 20,
        'responsive' => false,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.invoices.show',
        'panel' => 'admin',
        'kind' => 'show',
        'params' => static fn (?object $fixture = null): array => ['invoice' => $first(\App\Models\Finance\Invoice::class)],
        'permissions' => ['invoices.view'],
        'module' => 'invoices',
        'owner_phase' => 13,
        'query_budget' => 20,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.payment-methods.create',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['payment_methods.create'],
        'module' => 'payment_methods',
        'owner_phase' => 13,
        'query_budget' => 20,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.payment-methods.edit',
        'panel' => 'admin',
        'kind' => 'form',
        'params' => static fn (?object $fixture = null): array => ['method' => $first(\App\Models\Finance\PaymentMethodOption::class)],
        'permissions' => ['payment_methods.edit'],
        'module' => 'payment_methods',
        'owner_phase' => 13,
        'query_budget' => 20,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.payment-methods.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['payment_methods.view_any'],
        'module' => 'payment_methods',
        'owner_phase' => 13,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.payments.export',
        'panel' => 'admin',
        'kind' => 'export',
        'params' => static fn (?object $fixture = null): array => ['format' => 'csv'],
        'permissions' => ['payments.export', 'payments.view_financial'],
        'module' => 'payments',
        'owner_phase' => 13,
        'query_budget' => 20,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'csv',
    ],

    [
        'route' => 'admin.payments.index',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['payments.view_any', 'payments.view_financial'],
        'module' => 'payments',
        'owner_phase' => 13,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.reports.finance.expenses',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['expenses.view_reports', 'expenses.view_financial'],
        'module' => 'reports',
        'owner_phase' => 13,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.reports.finance.export',
        'panel' => 'admin',
        'kind' => 'export',
        'params' => static fn (?object $fixture = null): array => ['report' => 'income', 'format' => 'csv'],
        'permissions' => ['reports.view_reports'],
        'module' => 'reports',
        'owner_phase' => 13,
        'query_budget' => 20,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => null],
        'response' => 'csv',
    ],

    [
        'route' => 'admin.reports.finance.income',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['income.view_reports', 'income.view_financial'],
        'module' => 'reports',
        'owner_phase' => 13,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.reports.finance.index',
        'panel' => 'admin',
        'kind' => 'dashboard',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['reports.view_reports'],
        'module' => 'reports',
        'owner_phase' => 13,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.reports.finance.profit-loss',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['income.view_reports', 'income.view_financial', 'expenses.view_financial'],
        'module' => 'reports',
        'owner_phase' => 13,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'admin.reports.finance.receivables-aging',
        'panel' => 'admin',
        'kind' => 'index',
        'params' => static fn (?object $fixture = null): array => [],
        'permissions' => ['invoices.view_reports', 'invoices.view_financial'],
        'module' => 'reports',
        'owner_phase' => 13,
        'query_budget' => 25,
        'responsive' => true,
        'a11y' => true,
        'idor' => ['owner' => null],
        'response' => 'html',
    ],

    [
        'route' => 'site.invoices.pdf',
        'panel' => 'public',
        'kind' => 'export',
        'params' => static fn (?object $fixture = null): array => ['token' => (string) \App\Models\Finance\Invoice::query()->whereNotNull('public_token')->value('public_token')],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 13,
        'query_budget' => 20,
        'responsive' => false,
        'a11y' => false,
        'idor' => ['owner' => 'client_id'],
        'response' => 'csv',
        'expect' => 404,
    ],

    [
        'route' => 'site.invoices.view',
        'panel' => 'public',
        'kind' => 'public',
        'params' => static fn (?object $fixture = null): array => ['token' => (string) \App\Models\Finance\Invoice::query()->whereNotNull('public_token')->value('public_token')],
        'permissions' => [],
        'module' => null,
        'owner_phase' => 13,
        'query_budget' => 20,
        'responsive' => false,
        'a11y' => true,
        'idor' => ['owner' => 'client_id'],
        'response' => 'html',
    ],

];
