<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Phase 7 · §2.23 — payroll_runs: requirement §28's monthly run, generated and then **locked**.
 *
 * `locked_at` is the immutability line (HR-15). After it, every money column, component row and snapshot
 * on every item is frozen, the period's attendance is locked with it (HR-18), and there is deliberately
 * **no unlock** — an unlock is an edit of paid money with extra steps ([D-HR-6]). A wrong slip is fixed
 * by a correction run that references the original.
 *
 * `day_basis`, `lop_basis`, `tax_mode` and `settings_snapshot` are **snapshots of the settings that
 * influenced the calculation**. Somebody changing `hr.payroll_day_basis` next year must not silently
 * change what last March's slip means, and without the snapshot it would.
 *
 * `regular_guard` (step 18) carries `uq_pr_regular`: one live regular run per branch per month, so a
 * second March payroll cannot be generated by accident while the first exists.
 *
 * **No `deleted_at`** (D16, D19): cancellation is a status.
 */
return new class extends Migration
{
    private const TABLE = 'payroll_runs';

    public function up(): void
    {
        if (Schema::hasTable(self::TABLE)) {
            return;
        }

        Schema::create(self::TABLE, function (Blueprint $table): void {
            $table->id();
            $table->string('run_number', 32);
            $table->string('title', 150)->nullable();
            $table->foreignId('branch_id')->nullable()->constrained('branches')->nullOnDelete();
            $table->string('run_type', 24)->default('regular');
            $table->foreignId('parent_run_id')->nullable()->constrained('payroll_runs')->nullOnDelete();
            $table->unsignedSmallInteger('period_year');
            $table->unsignedTinyInteger('period_month');
            $table->date('period_start');
            $table->date('period_end');
            $table->date('payment_date')->nullable();
            $table->string('status', 24)->default('draft');

            $table->unsignedInteger('employee_count')->default(0);
            $table->decimal('total_gross', 15, 2)->default(0);
            $table->decimal('total_deductions', 15, 2)->default(0);
            $table->decimal('total_net', 15, 2)->default(0);
            $table->decimal('total_paid', 15, 2)->default(0);

            // Snapshots of the settings that shaped the calculation, so a slip is reproducible years later.
            $table->string('day_basis', 16);
            $table->string('lop_basis', 16);
            $table->string('tax_mode', 16);
            $table->json('settings_snapshot')->nullable();

            $table->timestamp('generated_at')->nullable();
            $table->foreignId('generated_by')->nullable()->constrained('users')->nullOnDelete();
            // The immutability line (HR-15). There is no unlock.
            $table->timestamp('locked_at')->nullable();
            $table->foreignId('locked_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('paid_at')->nullable();
            $table->timestamp('cancelled_at')->nullable();
            $table->foreignId('cancelled_by')->nullable()->constrained('users')->nullOnDelete();
            $table->string('cancellation_reason', 255)->nullable();
            $table->text('notes')->nullable();
            // regular_guard (generated STORED) and uq_pr_regular are added in step 18.

            $table->timestamps();
            // No softDeletes(): cancellation is a status (D16, D19).
            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();

            // §2.23 Keys.
            $table->unique('run_number', 'uq_pr_number');
            $table->index(['period_year', 'period_month', 'status']);
            $table->index(['status', 'locked_at']);
            $table->index(['branch_id', 'period_year', 'period_month']);
            $table->index('parent_run_id');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists(self::TABLE);
    }
};
