<?php

declare(strict_types=1);

namespace App\Models\Institute;

use App\Enums\SubmissionStatus;
use App\Models\Concerns\Blameable;
use App\Models\Concerns\LogsActivityWithContext;
use App\Models\User;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use LogicException;

/**
 * One student's work on one assignment (phase-19-23 §2.7, requirement §80).
 *
 * **A resubmission supersedes; it never overwrites.** The previous attempt keeps its files, its marks
 * and its timestamps, and gains `status = superseded` plus a `superseded_by_id` pointing forward. That
 * is what makes "I submitted this on the 3rd" answerable a term later, and it is why the history is a
 * chain of rows rather than a `version` column on one.
 *
 * **INV-19-5 — one live submission per (assignment, student) — is enforced by `current_guard`**, a
 * generated column that is `1` for every live status and NULL for `superseded`. MariaDB permits
 * unlimited NULLs in a unique index, so `uq_as_live` allows the history to stack while permitting
 * exactly one live row. `current_guard` is read-only here; it follows `status` automatically, and
 * anything that tried to set it would be trying to lie about which attempt is current.
 *
 * **INV-19-7 — `is_late` and `minutes_late` are decided once, at insert, and never recomputed.** The
 * hook below refuses to move them. A teacher extending a deadline afterwards is setting a new deadline
 * for whoever has not submitted; it is not a statement that nobody was ever late. Recomputing would
 * rewrite history and take the late count with it.
 *
 * **`final_marks` is generated by the database** as `GREATEST(obtained - penalty, 0)`, so it cannot
 * drift from its inputs and cannot be edited into disagreeing with them.
 *
 * **Nothing deletes a submission** (§2.7): the policy returns false for `delete` and `forceDelete` for
 * every role, `restrictOnDelete` backs it on both parents, and the hook below refuses it outright —
 * because `Gate::before` lets a Super Admin past a policy, and marked work is not something anybody's
 * permissions should be able to remove. A student may withdraw only while the row is still a draft.
 *
 * @property SubmissionStatus $status
 * @property string $total_marks
 */
class AssignmentSubmission extends Model
{
    use Blameable;
    use LogsActivityWithContext;
    use SoftDeletes;

    /** INV-19-7: written at insert, never moved afterwards. */
    private const DECIDED_AT_INSERT = ['is_late', 'minutes_late', 'attempt_no'];

    protected $table = 'assignment_submissions';

    /**
     * A student may set their text and nothing else. Every mark, every timestamp, the lateness and the
     * roster proof are composed by `AssignmentSubmissionService` — a submission that could
     * mass-assign `obtained_marks` would be a student grading themselves.
     *
     * This also keeps `final_marks` and `current_guard` out of every write: they are generated
     * columns, and an INSERT that named them would be rejected by the server.
     *
     * @var list<string>
     */
    protected $fillable = [
        'submission_text',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'assignment_id' => 'integer',
            'student_id' => 'integer',
            'student_batch_enrollment_id' => 'integer',
            'batch_id' => 'integer',
            'attempt_no' => 'integer',
            'files_count' => 'integer',
            'status' => SubmissionStatus::class,
            'submitted_at' => 'immutable_datetime',
            'is_late' => 'boolean',
            'minutes_late' => 'integer',
            'obtained_marks' => 'decimal:2',
            'penalty_marks' => 'decimal:2',
            'final_marks' => 'decimal:2',
            'total_marks' => 'decimal:2',
            'percentage' => 'decimal:4',
            'is_passed' => 'boolean',
            'graded_by' => 'integer',
            'graded_at' => 'immutable_datetime',
            'returned_at' => 'immutable_datetime',
            'marks_released_at' => 'immutable_datetime',
            'superseded_by_id' => 'integer',
            'amended_at' => 'immutable_datetime',
            'amended_by' => 'integer',
        ];
    }

    protected static function booted(): void
    {
        static::updating(static function (self $submission): void {
            $moved = array_intersect(array_keys($submission->getDirty()), self::DECIDED_AT_INSERT);

            if ($moved !== []) {
                throw new LogicException(sprintf(
                    'Submission #%s had %s decided when it was handed in and they are not recomputed '
                    .'(INV-19-7). Moving a deadline changes what happens next, not what already did.',
                    (string) $submission->getKey(),
                    implode(' and ', $moved),
                ));
            }
        });

        // Soft delete or hard, and whoever is asking. Marked work is somebody's record.
        static::deleting(static function (self $submission): never {
            throw new LogicException(sprintf(
                'Submission #%s is never deleted (§2.7). A draft is withdrawn and a replaced attempt '
                .'is superseded; both keep their row.',
                (string) $submission->getKey(),
            ));
        });
    }

    public function moduleSlug(): string
    {
        return 'assignment_submissions';
    }

    protected function activityModule(): ?string
    {
        return 'assignment_submissions';
    }

    /** INV-19-5: this is the current attempt. Reads the generated column, so it cannot disagree. */
    public function isLive(): bool
    {
        return $this->getAttribute('current_guard') !== null;
    }

    public function isDraft(): bool
    {
        return $this->status === SubmissionStatus::Draft;
    }

    /**
     * Whether the **student** may see their mark. Three separate gates, all of which must hold: the
     * row is graded, the assignment is willing to show marks at all, and this row has been released.
     * A teacher marking a batch privately and releasing it in one go depends on all three.
     */
    public function marksVisibleToStudent(): bool
    {
        return $this->status->visibleMarks()
            && $this->getAttribute('marks_released_at') !== null
            && (bool) $this->assignment?->getAttribute('marks_visible_to_students');
    }

    /** A mark that was changed after the student had already seen it — always with a reason. */
    public function wasAmended(): bool
    {
        return $this->getAttribute('amended_at') !== null;
    }

    /** The live attempts only: superseded rows have a NULL guard. */
    public function scopeLive(Builder $query): Builder
    {
        return $query->whereNotNull('current_guard');
    }

    public function scopeForStudent(Builder $query, int $studentId): Builder
    {
        return $query->where('student_id', $studentId);
    }

    public function assignment(): BelongsTo
    {
        return $this->belongsTo(Assignment::class, 'assignment_id');
    }

    public function student(): BelongsTo
    {
        return $this->belongsTo(Student::class, 'student_id');
    }

    /** The roster proof: this student was enrolled on this batch when they submitted. */
    public function enrollment(): BelongsTo
    {
        return $this->belongsTo(StudentBatchEnrollment::class, 'student_batch_enrollment_id');
    }

    public function batch(): BelongsTo
    {
        return $this->belongsTo(Batch::class, 'batch_id');
    }

    public function grader(): BelongsTo
    {
        return $this->belongsTo(User::class, 'graded_by');
    }

    public function amender(): BelongsTo
    {
        return $this->belongsTo(User::class, 'amended_by');
    }

    /** The attempt that replaced this one. Unique, so the chain cannot fork. */
    public function supersededBy(): BelongsTo
    {
        return $this->belongsTo(self::class, 'superseded_by_id');
    }

    public function files(): HasMany
    {
        return $this->hasMany(AssignmentSubmissionFile::class, 'assignment_submission_id');
    }
}
